# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5e23774dc6779e0a76c2eed92c98a9f2"
name = "Zupli-Beta"
application_url = "https://zupli-beta.onrender.com/"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/order_create"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/create_subscription"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/webhooks/app/shop_currenacy_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_discounts,read_markets,read_orders,read_products,write_app_proxy,write_cart_transforms,write_discounts,write_orders,write_products"

[auth]
redirect_urls = [
  "https://zupli-beta.onrender.com/auth",
  "https://zupli-beta.onrender.com/auth/login",
  "https://zupli-beta.onrender.com/auth/callback"
]

[app_proxy]
url = "https://zupli-beta.onrender.com/optimaio-cart"
subpath = "optimaio-cart"
prefix = "apps"