# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cdf63c69b617cd8b34e1ccc4c8fe7027"
name = "Zupli"
application_url = "https://remix-app-rqyv.onrender.com/app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/webhooks/app/shop_currenacy_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/order_create"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/create_subscription"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_discounts,read_markets,read_orders,read_products,write_app_proxy,write_cart_transforms,write_discounts,write_orders,write_products,read_customers"

[auth]
redirect_urls = [
  "https://remix-app-rqyv.onrender.com/auth",
  "https://remix-app-rqyv.onrender.com/auth/login",
  "https://remix-app-rqyv.onrender.com/auth/callback"
]

[app_proxy]
url = "https://remix-app-rqyv.onrender.com/optimaio-cart"
subpath = "optimaio-cart"
prefix = "apps"
