# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3428b8c2fee4188e0d23198c99a0b615"
name = "optimaio cart"
application_url = "https://remix-app-rqyv.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"


  [[webhooks.subscriptions]]
  topics = ["markets/create"]
  uri = "/webhooks/app/markets_info"

  [[webhooks.subscriptions]]
  topics = ["markets/update"]
  uri = "/webhooks/app/markets_info"

  [[webhooks.subscriptions]]
  topics = ["markets/delete"]
  uri = "/webhooks/app/markets_info"

    [[webhooks.subscriptions]]
  topics = [ "carts/create" ]
  uri = "/webhooks/app/cart_create"

   [[webhooks.subscriptions]]
  topics = [ "carts/update" ]
  uri = "/webhooks/app/cart_update"

  [app_proxy]
url = "/optimaio-cart"
prefix = "apps"
subpath = "optimaio-cart"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_discounts,write_discounts,write_cart_transforms,write_app_proxy,read_content,read_markets,write_orders,read_orders"


[auth]
redirect_urls = ["https://remix-app-rqyv.onrender.com/auth/callback"]
#[build]
#automatically_update_urls_on_dev = true
